config/routes.rb
Rails.application.routes.draw do
root'rooms#index'
resources :rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :stations, inverse_of: :room, :dependent => :destroy
  accepts_nested_attributes_for :stations, allow_destroy: false, limit: 3
end

app/models/station.rb
class Station < ApplicationRecord
  belongs_to :room, inverse_of: :stations
  validates_presence_of :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  def index
    @rooms = Room.all
  end

  def show
    @stations = @room.stations
  end

  def new
    @room = Room.new
    2.times{@room.stations.build}
     
  end

  def edit
    @room.stations.build
  end

  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

 def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   
    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:name, :rent, :address, :age, :content, 
                                   stations_attributes:[:line, :minute, :name, :id, :room_id, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevExam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label"object" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label "loyer" %>
    <%= form.text_field :rent %>
  </div>

  <div class="field">
    <%= form.label "residence" %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label "Number of years" %>
    <%= form.text_field :age %>
  </div>

  <div class="field line">
    <%= form.label "pro forma" %>
    <%= form.text_area :content %>
  </div>

  <hr>

  
  <% n = 0 %>
  <%= form.fields_for :stations do |s| %>
  <h3>
  <%= "nearest station #{n += 1}" %>
  </h3>
  
  <div class="field">
    <%= s.label "line name" %>
    <%= s.text_field :line %>
  </div>

  <div class="field">
    <%= s.label "station name" %>
    <%= s.text_field :name %>
  </div>

  <div class="field">
    <%= s.label "number of steps" %>
    <%= s.text_field :minute %>
  </div>
  <% end %>
  
 
  
  <% if action_name == "new" %>
  <div class="actions">
    <%= form.submit "Register" %>
  </div>
  <% else %>
  <div class="actions">
    <%= form.submit "Update." %>
  </div>
  <% end %>
<% end %>

app/views/rooms/edit.html.erb
<h1>Object collection</h1>

<%= render 'form', room: @room %>

<%= link_to 'Details', @room %> |
<%= link_to 'back', rooms_path %>

app/views/rooms/index.html.erb
<h2 class="line">look</h2>
<hr>
<p id="notice"><%= notice %></p>

<h1>Object list</h1>

<table>
  <thead>
    <tr>
      <th>object name</th>
      <th>leasing</th>
      <th>residence</th>
      <th>Number of years</th>
      <th>pro forma</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.rent %></td>
        <td><%= room.address %></td>
        <td><%= room.age %></td>
        <td><%= room.content %></td>
        <td><%= link_to 'Details', room %></td>
        <td><%= link_to 'Editing', edit_room_path(room) %></td>
        <td><%= link_to 'delete', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Register your property', new_room_path %>

app/views/rooms/new.html.erb
<h3>register</h3>
<div class="right">
<h1>Registration</h1>

<%= render 'form', room: @room %>

<%= link_to 'back', rooms_path %>
</div>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Browse</2>
<p>
  <strong>object name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>leasing:</strong>
  <%= @room.rent %>
</p>

<p>
  <strong>residence:</strong>
  <%= @room.address %>
</p>

<p>
  <strong>Number of years</strong>
  <%= @room.age %>
</p>

<p>
  <strong>pro forma</strong>
  <%= @room.content %>
</p>

<hr>
<% n = 0 %>
<% @stations.each do |station| %>
<h3>
<%= "nearest station#{n += 1}" %>
</h3>


<p>
  <strong>line name</strong>
  <%= station.line %>
</p>

<p>
  <strong>station name</strong>
  <%= station.name %>
</p>

<p>
  <strong>number of steps</strong>
  <%= station.minute %>
</p>

<% end %>

<%= link_to 'editing', edit_room_path(@room) %> |
<%= link_to 'return', rooms_path %>